apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: keda
  labels:
    deploymentName: kafka-consumer
spec:
  scaleTargetRef:
    name: kafka-consumer
  pollingInterval: 15
  cooldownPeriod: 60
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kedans.servicebus.windows.net:9093
        consumerGroup: group_keda
        topic: keda
        lagThreshold: "50"
        sasl: plaintext
      authenticationRef:
        name: eventhub-kafka-triggerauth
