apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-scaledobject
  namespace: keda-demo
  labels:
    deploymentName: kafka-consumer
spec:
  scaleTargetRef:
    name: kafka-consumer
  pollingInterval: 5
  cooldownPeriod: 10
  fallback:
    failureThreshold: 3
    replicas: 2
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kedans.servicebus.windows.net:9093
        consumerGroup: group_keda
        topic: keda
        lagThreshold: "50"
        sasl: plaintext
      authenticationRef:
        name: eventhub-kafka-triggerauth
