apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-consumer
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-consumer
  targetCPUUtilizationPercentage: 50